// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GopmClient is the client API for Gopm service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GopmClient interface {
	GetVersion(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*VersionResponse, error)
	GetProcessInfo(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ProcessInfoResponse, error)
	StartProcess(ctx context.Context, in *StartStopRequest, opts ...grpc.CallOption) (*StartStopResponse, error)
	StopProcess(ctx context.Context, in *StartStopRequest, opts ...grpc.CallOption) (*StartStopResponse, error)
	RestartProcess(ctx context.Context, in *StartStopRequest, opts ...grpc.CallOption) (*StartStopResponse, error)
	StartAllProcesses(ctx context.Context, in *StartStopAllRequest, opts ...grpc.CallOption) (*ProcessInfoResponse, error)
	StopAllProcesses(ctx context.Context, in *StartStopAllRequest, opts ...grpc.CallOption) (*ProcessInfoResponse, error)
	Shutdown(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ReloadConfig(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ReloadConfigResponse, error)
	TailLog(ctx context.Context, in *TailLogRequest, opts ...grpc.CallOption) (Gopm_TailLogClient, error)
	SignalProcess(ctx context.Context, in *SignalProcessRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	SignalProcessGroup(ctx context.Context, in *SignalProcessRequest, opts ...grpc.CallOption) (*ProcessInfoResponse, error)
	SignalAllProcesses(ctx context.Context, in *SignalProcessRequest, opts ...grpc.CallOption) (*ProcessInfoResponse, error)
}

type gopmClient struct {
	cc grpc.ClientConnInterface
}

func NewGopmClient(cc grpc.ClientConnInterface) GopmClient {
	return &gopmClient{cc}
}

func (c *gopmClient) GetVersion(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*VersionResponse, error) {
	out := new(VersionResponse)
	err := c.cc.Invoke(ctx, "/gopm.rpc.Gopm/GetVersion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gopmClient) GetProcessInfo(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ProcessInfoResponse, error) {
	out := new(ProcessInfoResponse)
	err := c.cc.Invoke(ctx, "/gopm.rpc.Gopm/GetProcessInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gopmClient) StartProcess(ctx context.Context, in *StartStopRequest, opts ...grpc.CallOption) (*StartStopResponse, error) {
	out := new(StartStopResponse)
	err := c.cc.Invoke(ctx, "/gopm.rpc.Gopm/StartProcess", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gopmClient) StopProcess(ctx context.Context, in *StartStopRequest, opts ...grpc.CallOption) (*StartStopResponse, error) {
	out := new(StartStopResponse)
	err := c.cc.Invoke(ctx, "/gopm.rpc.Gopm/StopProcess", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gopmClient) RestartProcess(ctx context.Context, in *StartStopRequest, opts ...grpc.CallOption) (*StartStopResponse, error) {
	out := new(StartStopResponse)
	err := c.cc.Invoke(ctx, "/gopm.rpc.Gopm/RestartProcess", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gopmClient) StartAllProcesses(ctx context.Context, in *StartStopAllRequest, opts ...grpc.CallOption) (*ProcessInfoResponse, error) {
	out := new(ProcessInfoResponse)
	err := c.cc.Invoke(ctx, "/gopm.rpc.Gopm/StartAllProcesses", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gopmClient) StopAllProcesses(ctx context.Context, in *StartStopAllRequest, opts ...grpc.CallOption) (*ProcessInfoResponse, error) {
	out := new(ProcessInfoResponse)
	err := c.cc.Invoke(ctx, "/gopm.rpc.Gopm/StopAllProcesses", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gopmClient) Shutdown(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/gopm.rpc.Gopm/Shutdown", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gopmClient) ReloadConfig(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ReloadConfigResponse, error) {
	out := new(ReloadConfigResponse)
	err := c.cc.Invoke(ctx, "/gopm.rpc.Gopm/ReloadConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gopmClient) TailLog(ctx context.Context, in *TailLogRequest, opts ...grpc.CallOption) (Gopm_TailLogClient, error) {
	stream, err := c.cc.NewStream(ctx, &Gopm_ServiceDesc.Streams[0], "/gopm.rpc.Gopm/TailLog", opts...)
	if err != nil {
		return nil, err
	}
	x := &gopmTailLogClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Gopm_TailLogClient interface {
	Recv() (*TailLogResponse, error)
	grpc.ClientStream
}

type gopmTailLogClient struct {
	grpc.ClientStream
}

func (x *gopmTailLogClient) Recv() (*TailLogResponse, error) {
	m := new(TailLogResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *gopmClient) SignalProcess(ctx context.Context, in *SignalProcessRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/gopm.rpc.Gopm/SignalProcess", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gopmClient) SignalProcessGroup(ctx context.Context, in *SignalProcessRequest, opts ...grpc.CallOption) (*ProcessInfoResponse, error) {
	out := new(ProcessInfoResponse)
	err := c.cc.Invoke(ctx, "/gopm.rpc.Gopm/SignalProcessGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gopmClient) SignalAllProcesses(ctx context.Context, in *SignalProcessRequest, opts ...grpc.CallOption) (*ProcessInfoResponse, error) {
	out := new(ProcessInfoResponse)
	err := c.cc.Invoke(ctx, "/gopm.rpc.Gopm/SignalAllProcesses", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GopmServer is the server API for Gopm service.
// All implementations must embed UnimplementedGopmServer
// for forward compatibility
type GopmServer interface {
	GetVersion(context.Context, *emptypb.Empty) (*VersionResponse, error)
	GetProcessInfo(context.Context, *emptypb.Empty) (*ProcessInfoResponse, error)
	StartProcess(context.Context, *StartStopRequest) (*StartStopResponse, error)
	StopProcess(context.Context, *StartStopRequest) (*StartStopResponse, error)
	RestartProcess(context.Context, *StartStopRequest) (*StartStopResponse, error)
	StartAllProcesses(context.Context, *StartStopAllRequest) (*ProcessInfoResponse, error)
	StopAllProcesses(context.Context, *StartStopAllRequest) (*ProcessInfoResponse, error)
	Shutdown(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	ReloadConfig(context.Context, *emptypb.Empty) (*ReloadConfigResponse, error)
	TailLog(*TailLogRequest, Gopm_TailLogServer) error
	SignalProcess(context.Context, *SignalProcessRequest) (*emptypb.Empty, error)
	SignalProcessGroup(context.Context, *SignalProcessRequest) (*ProcessInfoResponse, error)
	SignalAllProcesses(context.Context, *SignalProcessRequest) (*ProcessInfoResponse, error)
	mustEmbedUnimplementedGopmServer()
}

// UnimplementedGopmServer must be embedded to have forward compatible implementations.
type UnimplementedGopmServer struct {
}

func (UnimplementedGopmServer) GetVersion(context.Context, *emptypb.Empty) (*VersionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVersion not implemented")
}
func (UnimplementedGopmServer) GetProcessInfo(context.Context, *emptypb.Empty) (*ProcessInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProcessInfo not implemented")
}
func (UnimplementedGopmServer) StartProcess(context.Context, *StartStopRequest) (*StartStopResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartProcess not implemented")
}
func (UnimplementedGopmServer) StopProcess(context.Context, *StartStopRequest) (*StartStopResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopProcess not implemented")
}
func (UnimplementedGopmServer) RestartProcess(context.Context, *StartStopRequest) (*StartStopResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RestartProcess not implemented")
}
func (UnimplementedGopmServer) StartAllProcesses(context.Context, *StartStopAllRequest) (*ProcessInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartAllProcesses not implemented")
}
func (UnimplementedGopmServer) StopAllProcesses(context.Context, *StartStopAllRequest) (*ProcessInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopAllProcesses not implemented")
}
func (UnimplementedGopmServer) Shutdown(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedGopmServer) ReloadConfig(context.Context, *emptypb.Empty) (*ReloadConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReloadConfig not implemented")
}
func (UnimplementedGopmServer) TailLog(*TailLogRequest, Gopm_TailLogServer) error {
	return status.Errorf(codes.Unimplemented, "method TailLog not implemented")
}
func (UnimplementedGopmServer) SignalProcess(context.Context, *SignalProcessRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignalProcess not implemented")
}
func (UnimplementedGopmServer) SignalProcessGroup(context.Context, *SignalProcessRequest) (*ProcessInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignalProcessGroup not implemented")
}
func (UnimplementedGopmServer) SignalAllProcesses(context.Context, *SignalProcessRequest) (*ProcessInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignalAllProcesses not implemented")
}
func (UnimplementedGopmServer) mustEmbedUnimplementedGopmServer() {}

// UnsafeGopmServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GopmServer will
// result in compilation errors.
type UnsafeGopmServer interface {
	mustEmbedUnimplementedGopmServer()
}

func RegisterGopmServer(s grpc.ServiceRegistrar, srv GopmServer) {
	s.RegisterService(&Gopm_ServiceDesc, srv)
}

func _Gopm_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GopmServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gopm.rpc.Gopm/GetVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GopmServer).GetVersion(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gopm_GetProcessInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GopmServer).GetProcessInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gopm.rpc.Gopm/GetProcessInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GopmServer).GetProcessInfo(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gopm_StartProcess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartStopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GopmServer).StartProcess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gopm.rpc.Gopm/StartProcess",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GopmServer).StartProcess(ctx, req.(*StartStopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gopm_StopProcess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartStopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GopmServer).StopProcess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gopm.rpc.Gopm/StopProcess",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GopmServer).StopProcess(ctx, req.(*StartStopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gopm_RestartProcess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartStopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GopmServer).RestartProcess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gopm.rpc.Gopm/RestartProcess",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GopmServer).RestartProcess(ctx, req.(*StartStopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gopm_StartAllProcesses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartStopAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GopmServer).StartAllProcesses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gopm.rpc.Gopm/StartAllProcesses",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GopmServer).StartAllProcesses(ctx, req.(*StartStopAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gopm_StopAllProcesses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartStopAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GopmServer).StopAllProcesses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gopm.rpc.Gopm/StopAllProcesses",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GopmServer).StopAllProcesses(ctx, req.(*StartStopAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gopm_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GopmServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gopm.rpc.Gopm/Shutdown",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GopmServer).Shutdown(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gopm_ReloadConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GopmServer).ReloadConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gopm.rpc.Gopm/ReloadConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GopmServer).ReloadConfig(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gopm_TailLog_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TailLogRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GopmServer).TailLog(m, &gopmTailLogServer{stream})
}

type Gopm_TailLogServer interface {
	Send(*TailLogResponse) error
	grpc.ServerStream
}

type gopmTailLogServer struct {
	grpc.ServerStream
}

func (x *gopmTailLogServer) Send(m *TailLogResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Gopm_SignalProcess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignalProcessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GopmServer).SignalProcess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gopm.rpc.Gopm/SignalProcess",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GopmServer).SignalProcess(ctx, req.(*SignalProcessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gopm_SignalProcessGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignalProcessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GopmServer).SignalProcessGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gopm.rpc.Gopm/SignalProcessGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GopmServer).SignalProcessGroup(ctx, req.(*SignalProcessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gopm_SignalAllProcesses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignalProcessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GopmServer).SignalAllProcesses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gopm.rpc.Gopm/SignalAllProcesses",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GopmServer).SignalAllProcesses(ctx, req.(*SignalProcessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Gopm_ServiceDesc is the grpc.ServiceDesc for Gopm service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Gopm_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gopm.rpc.Gopm",
	HandlerType: (*GopmServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVersion",
			Handler:    _Gopm_GetVersion_Handler,
		},
		{
			MethodName: "GetProcessInfo",
			Handler:    _Gopm_GetProcessInfo_Handler,
		},
		{
			MethodName: "StartProcess",
			Handler:    _Gopm_StartProcess_Handler,
		},
		{
			MethodName: "StopProcess",
			Handler:    _Gopm_StopProcess_Handler,
		},
		{
			MethodName: "RestartProcess",
			Handler:    _Gopm_RestartProcess_Handler,
		},
		{
			MethodName: "StartAllProcesses",
			Handler:    _Gopm_StartAllProcesses_Handler,
		},
		{
			MethodName: "StopAllProcesses",
			Handler:    _Gopm_StopAllProcesses_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _Gopm_Shutdown_Handler,
		},
		{
			MethodName: "ReloadConfig",
			Handler:    _Gopm_ReloadConfig_Handler,
		},
		{
			MethodName: "SignalProcess",
			Handler:    _Gopm_SignalProcess_Handler,
		},
		{
			MethodName: "SignalProcessGroup",
			Handler:    _Gopm_SignalProcessGroup_Handler,
		},
		{
			MethodName: "SignalAllProcesses",
			Handler:    _Gopm_SignalAllProcesses_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "TailLog",
			Handler:       _Gopm_TailLog_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "service.proto",
}
