// Code generated by "stringer -type ProbeType"; DO NOT EDIT.

package config

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ProbeUnknown-0]
	_ = x[ProbeCommand-1]
	_ = x[ProbeURL-2]
	_ = x[ProbeFile-3]
	_ = x[ProbeOutput-4]
}

const _ProbeType_name = "ProbeUnknownProbeCommandProbeURLProbeFileProbeOutput"

var _ProbeType_index = [...]uint8{0, 12, 24, 32, 41, 52}

func (i ProbeType) String() string {
	if i < 0 || i >= ProbeType(len(_ProbeType_index)-1) {
		return "ProbeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ProbeType_name[_ProbeType_index[i]:_ProbeType_index[i+1]]
}
