// Code generated by "stringer -type depKind"; DO NOT EDIT.

package process

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[depDependsOn-1]
	_ = x[depDependedOn-2]
	_ = x[depTarget-4]
}

const (
	_depKind_name_0 = "depDependsOndepDependedOn"
	_depKind_name_1 = "depTarget"
)

var (
	_depKind_index_0 = [...]uint8{0, 12, 25}
)

func (i depKind) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _depKind_name_0[_depKind_index_0[i]:_depKind_index_0[i+1]]
	case i == 4:
		return _depKind_name_1
	default:
		return "depKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
