// Code generated by "stringer -type processRequestKind"; DO NOT EDIT.

package process

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[reqInvalid-0]
	_ = x[reqStart-1]
	_ = x[reqStop-2]
	_ = x[reqPause-3]
	_ = x[reqResume-4]
	_ = x[reqUpdate-5]
	_ = x[reqDepsReady-6]
	_ = x[reqInfo-7]
	_ = x[reqLogger-8]
	_ = x[reqSignal-9]
}

const _processRequestKind_name = "reqInvalidreqStartreqStopreqPausereqResumereqUpdatereqDepsReadyreqInforeqLoggerreqSignal"

var _processRequestKind_index = [...]uint8{0, 10, 18, 25, 33, 42, 51, 63, 70, 79, 88}

func (i processRequestKind) String() string {
	if i < 0 || i >= processRequestKind(len(_processRequestKind_index)-1) {
		return "processRequestKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _processRequestKind_name[_processRequestKind_index[i]:_processRequestKind_index[i+1]]
}
