// Code generated by "stringer -type processRequestKind"; DO NOT EDIT.

package process

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[reqInvalid-0]
	_ = x[reqUpdate-1]
	_ = x[reqStart-2]
	_ = x[reqStop-3]
	_ = x[reqRestart-4]
	_ = x[reqInfo-5]
	_ = x[reqLogger-6]
	_ = x[reqSignal-7]
}

const _processRequestKind_name = "reqInvalidreqUpdatereqStartreqStopreqRestartreqInforeqLoggerreqSignal"

var _processRequestKind_index = [...]uint8{0, 10, 19, 27, 34, 44, 51, 60, 69}

func (i processRequestKind) String() string {
	if i < 0 || i >= processRequestKind(len(_processRequestKind_index)-1) {
		return "processRequestKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _processRequestKind_name[_processRequestKind_index[i]:_processRequestKind_index[i+1]]
}
