// Code generated by "stringer -type State"; DO NOT EDIT.

package process

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Invalid-0]
	_ = x[Starting-1]
	_ = x[Running-2]
	_ = x[Backoff-3]
	_ = x[Stopping-4]
	_ = x[Pausing-5]
	_ = x[Paused-6]
	_ = x[Stopped-7]
	_ = x[Exited-8]
	_ = x[Fatal-9]
}

const _State_name = "InvalidStartingRunningBackoffStoppingPausingPausedStoppedExitedFatal"

var _State_index = [...]uint8{0, 7, 15, 22, 29, 37, 44, 50, 57, 63, 68}

func (i State) String() string {
	if i < 0 || i >= State(len(_State_index)-1) {
		return "State(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _State_name[_State_index[i]:_State_index[i+1]]
}
