name: Tests
on:
  push:
    branches:
    - master
    - feature-cue
  pull_request:
    branches:
    - master
    - feature-cue
jobs:
  go-test:
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.17.x]
        os: [ubuntu-latest, macos-latest]
    name: Go Test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
      id: go

    - name: Checkout
      uses: actions/checkout@v2

    - name: Test
      run: |
        go test ./...
        go test -race ./...

    - name: Tidy
      if: matrix.os == 'ubuntu-latest' # no need to do this everywhere
      run: |
        go mod tidy

        test -z "$(gofmt -d .)" || (gofmt -d . && false)
        test -z "$(git status --porcelain)" || (git status; git diff && false)
